# Generated by Django 5.2.6 on 2025-09-21 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('applicable_for', models.CharField(choices=[('kg_std', 'KG-STD'), ('plus_one', 'Plus One'), ('both', 'Both')], default='both', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='KgStdApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('previous_school', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_applying_for', models.CharField(max_length=50)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=50)),
                ('documents_submitted', models.BooleanField(default=False)),
                ('interview_scheduled', models.BooleanField(default=False)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KG-STD Application',
                'verbose_name_plural': 'KG-STD Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlusOneApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('previous_school', models.CharField(max_length=255)),
                ('sslc_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stream_preference', models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('humanities', 'Humanities')], max_length=100)),
                ('subjects_selected', models.TextField(help_text='Comma-separated list of subjects')),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=50)),
                ('documents_submitted', models.BooleanField(default=False)),
                ('entrance_exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interview_scheduled', models.BooleanField(default=False)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plus One Application',
                'verbose_name_plural': 'Plus One Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSubjectTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('practical', 'Practical'), ('oral', 'Oral')], default='short_answer', max_length=50)),
                ('options', models.JSONField(blank=True, help_text='For multiple choice questions', null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('marks', models.IntegerField(default=1)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='admissions.interviewsubject')),
            ],
            options={
                'ordering': ['subject', 'order_index', 'question_text'],
            },
        ),
    ]
