# Generated by Django 5.2.6 on 2025-09-21 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[("kg_std", "KG & STD"), ("plus_one", "+1 / HSS")],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("academic_year", models.CharField(max_length=10)),
            ],
        ),
    ]
