# Generated by Django 5.2.6 on 2025-09-21 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("photo_url", models.URLField(blank=True)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("order_index", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Board Member",
                "verbose_name_plural": "Board Members",
                "ordering": ["order_index", "name"],
            },
        ),
    ]
