# Generated by Django 5.2.6 on 2025-09-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_boardmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardmember",
            name="board_type",
            field=models.CharField(
                choices=[
                    ("governing_board", "Governing Board"),
                    ("board_of_directors", "Board of Directors"),
                ],
                default="governing_board",
                max_length=50,
            ),
        ),
    ]
