# Generated by Django 5.2.6 on 2025-09-21 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_boardmember_board_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadershipMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("person_name", models.CharField(max_length=255)),
                ("person_title", models.CharField(max_length=255)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("chairman", "Chairman"),
                            ("principal", "Principal"),
                            ("vice_principal", "Vice Principal"),
                            ("manager", "Manager"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message_content", models.TextField()),
                ("photo_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leadership Message",
                "verbose_name_plural": "Leadership Messages",
                "ordering": ["display_order", "person_name"],
            },
        ),
    ]
