// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbpakffkctwafthhoayp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicGFrZmZrY3R3YWZ0aGhvYXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDY0ODksImV4cCI6MjA3MDIyMjQ4OX0.NQlbiQ6KdQZNKTwVfstOc8kBW71DfplZcSlAYEQ9tGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});